services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # event: boot i18n
    I18nBundle\EventListener\I18nStartupListener:
        tags:
            - { name: kernel.event_subscriber }

    # event: define preview parameters
    I18nBundle\EventListener\I18nPreviewListener:
        tags:
            - { name: kernel.event_subscriber }

    # event: redirect user to given locale
    I18nBundle\EventListener\DetectorListener:
        tags:
            - { name: kernel.event_subscriber }

    # event: detect pimcore redirect
    I18nBundle\EventListener\PimcoreRedirectListener:
        tags:
            - { name: kernel.event_subscriber }

    # event: attach site in admin context (frontend edit mode)
    I18nBundle\EventListener\AdminSiteListener:
        tags:
            - { name: kernel.event_subscriber }

    # event: log context switch
    I18nBundle\EventListener\ContextSwitchDetectorListener:
        tags:
            - { name: kernel.event_subscriber }

     # event: checks if hardlink page has a front-page map
    I18nBundle\EventListener\Frontend\FrontPageMapperListener:
        tags:
            - { name: kernel.event_subscriber }

    # event: removes canonical Link tag from hardlink headers
    I18nBundle\EventListener\CanonicalListener:
        tags:
            - { name: kernel.event_subscriber }

    # event: adds i18n meta tags to HeadMeta view helper
    I18nBundle\EventListener\Frontend\HeadMetaListener:
        tags:
            - { name: kernel.event_subscriber }

    # event: adds i18n meta tags to HeadMeta view helper
    I18nBundle\EventListener\Frontend\HeadLinkListener:
        tags:
            - { name: kernel.event_subscriber }

    # override pimcore not found exception handling
    I18nBundle\EventListener\Frontend\ResponseExceptionListener:
        decorates: Pimcore\Bundle\CoreBundle\EventListener\ResponseExceptionListener
        calls:
            - [ setLogger, [ '@logger' ] ]
