services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    I18nBundle\Resolver\RedirectResolver: ~

    I18nBundle\Resolver\PimcoreAdminSiteResolverInterface: '@I18nBundle\Resolver\PimcoreAdminSiteResolver'
    I18nBundle\Resolver\PimcoreAdminSiteResolver: ~

    I18nBundle\Resolver\PimcoreDocumentResolverInterface: '@I18nBundle\Resolver\PimcoreDocumentResolver'
    I18nBundle\Resolver\PimcoreDocumentResolver: ~
