services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    I18nBundle\Tool\Install:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('I18nBundle')"

    I18nBundle\Configuration\Configuration: ~

    I18nBundle\Session\SessionConfigurator:
        tags:
            - { name: pimcore.session.configurator }

    I18nBundle\Routing\I18nRouter:
        decorates: 'router'
        arguments:
            $router: '@I18nBundle\Routing\I18nRouter.inner'
