services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    I18nBundle\Transformer\AlternateRouteItemTransformer: ~
    I18nBundle\Transformer\LinkGeneratorRouteItemTransformer: ~
