services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # twig extensions
    I18nBundle\Twig\Extension\I18nExtension:
        tags:
            - { name: twig.extension }