services:

    #
    # Adapter: LocaleProvider

    I18nBundle\Adapter\LocaleProvider\AbstractLocaleProvider:
        abstract: true
        autowire: true

    I18nBundle\Adapter\LocaleProvider\SystemLocaleProvider:
        parent: I18nBundle\Adapter\LocaleProvider\AbstractLocaleProvider
        tags:
            - { name: i18n.adapter.locale, alias: system }


    #
    # Adapter: PathGenerator

    I18nBundle\Adapter\PathGenerator\AbstractPathGenerator:
        abstract: true
        autowire: true
        calls:
            - [setAlternateRouteItemTransformer, ['@I18nBundle\Transformer\AlternateRouteItemTransformer']]

    I18nBundle\Adapter\PathGenerator\StaticRoute:
        parent: I18nBundle\Adapter\PathGenerator\AbstractPathGenerator
        arguments:
            - '@router'
            - '@event_dispatcher'
        tags:
            - { name: i18n.adapter.path.generator, alias: static_route }

    I18nBundle\Adapter\PathGenerator\Symfony:
        parent: I18nBundle\Adapter\PathGenerator\AbstractPathGenerator
        arguments:
            - '@router'
        tags:
            - { name: i18n.adapter.path.generator, alias: symfony }

    I18nBundle\Adapter\PathGenerator\Document:
        parent: I18nBundle\Adapter\PathGenerator\AbstractPathGenerator
        tags:
            - { name: i18n.adapter.path.generator, alias: document }


    #
    # Adapter: ReDirector

    I18nBundle\Adapter\Redirector\AbstractRedirector:
        abstract: true
        autowire: true

    I18nBundle\Adapter\Redirector\CookieRedirector:
        parent: I18nBundle\Adapter\Redirector\AbstractRedirector
        tags:
            - { name: i18n.adapter.redirector, alias: cookie, priority: 300 }

    I18nBundle\Adapter\Redirector\GeoRedirector:
        parent: I18nBundle\Adapter\Redirector\AbstractRedirector
        tags:
            - { name: i18n.adapter.redirector, alias: geo, priority: 200 }

    I18nBundle\Adapter\Redirector\FallbackRedirector:
        parent: I18nBundle\Adapter\Redirector\AbstractRedirector
        tags:
            - { name: i18n.adapter.redirector, alias: fallback, priority: 100 }