services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # event: i18n detector, register language / country. setup all managers. redirect user
    I18nBundle\EventListener\DetectorListener:
        tags:
            - { name: kernel.event_subscriber }

     # event: checks if hardlink page has a frontpage map
    I18nBundle\EventListener\FrontPageMapperListener:
        tags:
            - { name: kernel.event_subscriber }

    # event: check frontend path document
    I18nBundle\EventListener\Frontend\FrontendPathListener:
        tags:
            - { name: kernel.event_subscriber }

    # event: check frontend path staticroute
    I18nBundle\EventListener\Frontend\FrontendPathStaticRouteListener:
        tags:
            - { name: kernel.event_subscriber }

    # event: check link paths (correct link path when redirection in hardlink context)
    I18nBundle\EventListener\Frontend\LinkPathListener:
        tags:
            - { name: kernel.event_subscriber }

    # event: removes canonical Link tag from hardlink headers
    I18nBundle\EventListener\CanonicalListener:
        tags:
            - { name: kernel.event_subscriber }

    # event: adds i18n meta tags to HeadMeta view helper
    I18nBundle\EventListener\Frontend\HeadMetaListener:
        class: I18nBundle\EventListener\Frontend\HeadMetaListener
        tags:
            - { name: kernel.event_subscriber }

    # event: adds i18n meta tags to HeadMeta view helper
    I18nBundle\EventListener\Frontend\HeadLinkListener:
        tags:
            - { name: kernel.event_subscriber }

    # override pimcore not found exception handling
    I18nBundle\EventListener\ResponseExceptionListener:
        arguments:
            $renderErrorPage: '%pimcore.response_exception_listener.render_error_document%'
        tags:
            - { name: kernel.event_subscriber }