services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    I18nBundle\Helper\DocumentHelper: ~

    I18nBundle\Helper\CookieHelper: ~

    I18nBundle\Helper\UserHelper: ~