services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    I18nBundle\Helper\DocumentHelper: ~

    I18nBundle\Helper\CookieHelper: ~

    I18nBundle\Helper\RequestValidatorHelper: ~

    I18nBundle\Helper\UserHelper:
        arguments:
            $requestStack: '@request_stack'
            $geoIpDbPath: '%i18n.geo_ip.db_file%'
