services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # registry: locale provider
    I18nBundle\Registry\LocaleProviderRegistry:
        arguments:
            $interface: I18nBundle\Adapter\LocaleProvider\LocaleProviderInterface

    # registry: path generator
    I18nBundle\Registry\PathGeneratorRegistry:
        arguments:
            $interface: I18nBundle\Adapter\PathGenerator\PathGeneratorInterface

    # registry: redirector
    I18nBundle\Registry\RedirectorRegistry:
        arguments:
            $interface: I18nBundle\Adapter\Redirector\RedirectorInterface