services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    I18nBundle\Http\ZoneResolverInterface: '@I18nBundle\Http\ZoneResolver'
    I18nBundle\Http\ZoneResolver: ~
