services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    I18nBundle\Http\RouteItemResolverInterface: '@I18nBundle\Http\RouteItemResolver'
    I18nBundle\Http\RouteItemResolver: ~
