services:
    _defaults:
        autowire: true

    I18nBundle\Factory\RouteItemFactory: ~

    I18nBundle\Modifier\RouteModifier:
        autowire: true

    I18nBundle\Modifier\RouteItem\RouteItemModifier:
        arguments:
            - !tagged_iterator i18n.modifier.route_item

    I18nBundle\Modifier\RouteItem\Type\DocumentRouteModifier:
        tags:
            - { name: i18n.modifier.route_item }

    I18nBundle\Modifier\RouteItem\Type\StaticRouteModifier:
        tags:
            - { name: i18n.modifier.route_item }

    I18nBundle\Modifier\RouteItem\Type\SymfonyRouteModifier:
        tags:
            - { name: i18n.modifier.route_item }

    I18nBundle\Modifier\RouteItem\Type\RequestAwareModifier:
        tags:
            - { name: i18n.modifier.route_item }
