#!/bin/bash

export DACHCOM_BUNDLE_HOME=$GITHUB_WORKSPACE
export DACHCOM_BUNDLE_NAME="I18nBundle"
export DACHCOM_BUNDLE_REPO_NAME="i18n"

export DACHCOM_BUNDLE_CLASS='I18nBundle\I18nBundle'
export DACHCOM_BUNDLE_INSTALLER_CLASS='I18nBundle\Tool\Install'

declare -A DACHCOM_INSTALL_CONFIG_FILES=(
 # system files
 ["./tests/_etc/config/bundle/extensions.php.template"]="./var/config/extensions.php"
 ["./tests/_etc/config/bundle/system.yml.template"]="./var/config/system.yml"
 ["./tests/_etc/config/bundle/appKernel.php.template"]="./app/AppKernel.php"
 # template files
 ["./tests/_etc/config/bundle/template/controller/DefaultController"]="./src/AppBundle/Controller/DefaultController.php"
 ["./tests/_etc/config/bundle/template/views/default"]="./app/Resources/views/Default/default.html.twig"
 ["./tests/_etc/config/bundle/template/views/languageSelector"]="./app/Resources/views/Default/languageSelector.html.twig"
)