#!/usr/bin/env bash

export DACHCOM_BUNDLE_HOME=$TRAVIS_BUILD_DIR
export DACHCOM_BUNDLE_NAME="I18nBundle"
export DACHCOM_BUNDLE_REPO_NAME="i18n"
export DACHCOM_BUNDLE_COMMIT=$TRAVIS_COMMIT
export DACHCOM_BUNDLE_BRANCH=$TRAVIS_BRANCH

export DACHCOM_BUNDLE_CLASS='I18nBundle\I18nBundle'
export DACHCOM_BUNDLE_INSTALLER_CLASS='I18nBundle\Tool\Install'

declare -A DACHCOM_INSTALL_CONFIG_FILES=(
 # system files
 ["$DACHCOM_BUNDLE_HOME/_etc/config/bundle/extensions.php.template"]="var/config/extensions.php"
 ["$DACHCOM_BUNDLE_HOME/_etc/config/bundle/system.yml.template"]="var/config/system.yml"
 ["$DACHCOM_BUNDLE_HOME/_etc/config/bundle/appKernel.php.template"]="app/AppKernel.php"
 # template files
 ["$DACHCOM_BUNDLE_HOME/_etc/config/bundle/template/controller/DefaultController"]="src/AppBundle/Controller/DefaultController.php"
 ["$DACHCOM_BUNDLE_HOME/_etc/config/bundle/template/views/default"]="app/Resources/views/Default/default.html.twig"
)